---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(httr)
library(jsonlite)
library(plotly)

get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections = 
  get_all_inspections(url) %>%
  bind_rows() 
```

Column {data-width=650}
-----------------------------------------------------------------------

### American Restaurants in Manhattan by Street in longitude

```{r}
nyc_inspections |> 
  select(camis, boro, building, zipcode, critical_flag, score, census_tract, violation_description, grade, grade_date, latitude, longitude)
  
nyc_american =
  drop_na(nyc_inspections) |> 
  filter(cuisine_description == "American", 
         boro == "Manhattan",
         grade != "Z")

nyc_american |> 
  mutate(text_label = str_c("Grade: ", grade, "\nScore: ", score))|> 
  plot_ly(
    x = ~street, y = ~longitude, type = "scatter",
    color = ~grade, text = ~text_label, alpha = 0.5)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Number of A-Grade Restaurants by different types

```{r}
nyc_A = 
  drop_na(nyc_inspections) |> 
  filter(grade == "A") 

  
count(nyc_A, cuisine_description) |> 
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) |> 
  plot_ly(x = ~cuisine_description, y = ~n, color = ~cuisine_description, type = "bar", colors = "viridis") 
  
```

###  Critical Score of American Restaurants in Manhattan by 4 different Cuisine Types

```{r}
nyc_score =
  drop_na(nyc_inspections) |> 
  filter(boro == "Manhattan",
         grade != "Z",
         grade != "P",
         critical_flag == "Critical",
         cuisine_description == c("American","Chinese", "French","Thai"))

nyc_score |> 
plot_ly(x = ~cuisine_description, y = ~score, type = "box")
```

